openapi: 3.0.0
info:
  title: API test-service
  description: API тестового веб-сервиса
  version: 1.1.0

paths:

  /counter:
    get:
      operationId: getCounter
      tags:
        - Counter
      responses:
        '200':
          description: The current value of counter.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Counter'

  /increment:
    post:
      operationId: incrementCounter
      tags:
        - Counter
      responses:
        '200':
          description: Increment the current value of the counter and return the new value.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Counter'

  /reset:
    delete:
      operationId: resetCounter
      tags:
        - Counter
      responses:
        '200':
          description: Reset the current value of the counter and return 0.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Counter'


components:
  schemas:
    Counter:
      description: Класс-счетчик
      properties:
        value:
          description: Значение счетчика
          type: integer
          format: int32